INSERT INTO PATHINFO(SEQUENCE, URI, TITLE, PART, AUTHORITY, CREATEDAT)
VALUES(0, '/home', 'home', 'config', 'common', now());

INSERT INTO PATHINFO(SEQUENCE, URI, TITLE, PART, AUTHORITY, CREATEDAT)
VALUES(1, '/home/about', 'about', 'main', 'common', now());

INSERT INTO PATHINFO(SEQUENCE, URI, TITLE, PART, AUTHORITY, CREATEDAT)
VALUES(2, '/home/board', 'board', 'main', 'common', now());

INSERT INTO PATHINFO(SEQUENCE, URI, TITLE, PART, AUTHORITY, CREATEDAT)
VALUES(3, '/home/financial', 'financial', 'main', 'member', now());

INSERT INTO PATHINFO(SEQUENCE, URI, TITLE, PART, AUTHORITY, CREATEDAT)
VALUES(4, '/home/board/view', 'view', 'config', 'common', now());

INSERT INTO MEMBER(SEQUENCE, AUTHORITY, ACCOUNT, PASSWORD, NAME, CREATEDAT)
VALUES(NEXT VALUE FOR MEMBER_SEQUENCE, 'admin', 'TEST', 'TEST', 'TESTER', now());

INSERT INTO BOARD(SEQUENCE, CREATEDAT, MODIFIEDAT, PART, WRITER, TITLE, CONTENT)
VALUES(NEXT VALUE FOR BOARD_SEQUENCE, now(), now(), 'TEST', 'TESTER', 'TEST TITLE', 'TEST CONTENT');