DROP TABLE IF EXISTS PATHINFO;
CREATE TABLE PATHINFO (
    SEQUENCE    BIGINT,
    URI         VARCHAR2(255),
    TITLE       VARCHAR2(50),
    PART        VARCHAR2(50),
    AUTHORITY   VARCHAR2(10),
    CREATEDAT   DATE
);
DROP SEQUENCE IF EXISTS PATHINFO_SEQUENCE;
CREATE SEQUENCE PATHINFO_SEQUENCE;

DROP TABLE IF EXISTS BOARD;
CREATE TABLE BOARD (
    SEQUENCE        BIGINT,
    CREATEDAT       DATE,
    MODIFIEDAT      DATE,
    PART            VARCHAR2(50),
    WRITER          VARCHAR2(70),
    TITLE           VARCHAR2(255),
    CONTENT         CLOB
);
DROP SEQUENCE IF EXISTS BOARD_SEQUENCE;
CREATE SEQUENCE BOARD_SEQUENCE;

DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER (
    SEQUENCE    BIGINT,
    AUTHORITY   VARCHAR2(10),
    ACCOUNT     VARCHAR2(70),
    PASSWORD    VARCHAR2(255),
    NAME        VARCHAR2(70),
    CREATEDAT   DATE
);
DROP SEQUENCE IF EXISTS MEMBER_SEQUENCE;
CREATE SEQUENCE MEMBER_SEQUENCE;